# Sample deployment options for https://origami-netlify-upload-test.netlify.app

# name: origami-netlify-upload-test
id: 59bca707-6a99-44b0-827d-024ba7d2ec73
site: !ori demo/site.ori/
token: !ori token.json/
